// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9B201pKzJPtRKmuTqhiXWLuzQRnPbTP0',
    appId: '1:544480669735:web:5d5c8832bea5f72ea45e02',
    messagingSenderId: '544480669735',
    projectId: 'flutproject-19c09',
    authDomain: 'flutproject-19c09.firebaseapp.com',
    storageBucket: 'flutproject-19c09.firebasestorage.app',
    measurementId: 'G-WCCWT98DM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZYG-hEniqR8sBp5yELRTPbONjQr0mbIE',
    appId: '1:544480669735:android:88fa124837f7aa33a45e02',
    messagingSenderId: '544480669735',
    projectId: 'flutproject-19c09',
    storageBucket: 'flutproject-19c09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjiSqyMQr2I5HmzBKEMlrbSO-gI0pD6zE',
    appId: '1:544480669735:ios:1e626c90b1aa9872a45e02',
    messagingSenderId: '544480669735',
    projectId: 'flutproject-19c09',
    storageBucket: 'flutproject-19c09.firebasestorage.app',
    iosBundleId: 'com.example.flutproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjiSqyMQr2I5HmzBKEMlrbSO-gI0pD6zE',
    appId: '1:544480669735:ios:1e626c90b1aa9872a45e02',
    messagingSenderId: '544480669735',
    projectId: 'flutproject-19c09',
    storageBucket: 'flutproject-19c09.firebasestorage.app',
    iosBundleId: 'com.example.flutproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9B201pKzJPtRKmuTqhiXWLuzQRnPbTP0',
    appId: '1:544480669735:web:85f50bd0be29f363a45e02',
    messagingSenderId: '544480669735',
    projectId: 'flutproject-19c09',
    authDomain: 'flutproject-19c09.firebaseapp.com',
    storageBucket: 'flutproject-19c09.firebasestorage.app',
    measurementId: 'G-M5532L44H8',
  );
}
